version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        SUPPRESS_TYPESCRIPT_ERRORS: true
    volumes:
      - ./frontend:/app
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=development
